version: '2'

services:
  api:
    build:
      context: .
    restart: always
    environment:
      ADDOK_URL: https://api-adresse.data.gouv.fr
    stop_signal: SIGINT
    ports:
      - 5000:5000
    networks:
      - backnet
    volumes:
      - ./data-coverage/:/data/

networks:
  backnet:
